version: "3.9"

services:  
  php:
    build: php/
    container_name: lemp_php
    volumes:
      - ./public_html/:/var/www/html
    expose:
      - "9000"
    restart: always
    networks:
      - web_network
  nginx:
    image: nginx:stable-alpine
    container_name: lemp_nginx
    volumes:
      - ./public_html/:/var/www/html
      - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - "1234:80" 
    restart: always
    networks:
      - web_network

networks:
  web_network:
    name: lemp
    driver: bridge    